### ISSUE TITLE
Please move this to your course assigned repo

### ISSUE THREAD

**Issue by sgoggins** [AndrewGillisSoftware/CS4060-Strings#1]
I am not able to leave comments, make small corrections/suggestions, or grade anonymously otherwise.

**Comment by sgoggins** [comment]
@AndrewGillisSoftware : Please do this TODAY. I'm putting all my comments in the private repos, and when there are small syntax errors I fix them instead of sending them back to you. Which would make more work for everyone. :)

**Comment by AndrewGillisSoftware** [comment]
I have fixed the issue and transferred the code and readmes.
